dist: trusty
sudo: false
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libpng-dev
            - libjpeg-dev
      env:
        - BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libpng-dev
            - libjpeg-dev
      env:
        - BUILD_TYPE=Release
    # - compiler: clang
    #   addons:
    #     apt:
    #       packages:
    #         - libpng-dev
    #         - libjpeg-dev
    #   env:
    #     - BUILD_TYPE=Debug
    # - compiler: clang
    #   addons:
    #     apt:
    #       packages:
    #         - libpng-dev
    #         - libjpeg-dev
    #   env:
    #     - BUILD_TYPE=Release
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Release
      osx_image: xcode12

before_install:
  ############################################################################
  # Setup support for local dependencies
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
      mkdir -p ${DEPS_DIR}/local
      export CXXFLAGS="-isystem ${DEPS_DIR}/local/include"
      export PKG_CONFIG_PATH=${DEPS_DIR}/local/lib/pkgconfig
      export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/local/lib"
      export LDFLAGS="-L${DEPS_DIR}/local/lib"

      if [[ "${CXX}" == "g++" ]]; then
        export CC=gcc-4.9
        export CXX=g++-4.9
      else
        export CC=clang-4.9
        export CXX=clang++-4.9
      fi
    fi

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  ############################################################################
  # Osx dependencies
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
      brew upgrade cmake
    fi

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      wget https://www.ffmpeg.org/releases/ffmpeg-4.4.tar.bz2
      tar xf ffmpeg-4.4.tar.bz2
      cd ffmpeg-4.4 && ./configure --prefix=/${DEPS_DIR}/local --disable-static --enable-shared --disable-avdevice --disable-doc --disable-htmlpages --disable-manpages --disable-programs --disable-encoders --disable-muxers --enable-swscale --disable-yasm --enable-protocol=file --enable-protocol=http --enable-iconv  && make -j4 install
      cd ..
    fi

script:
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_STATIC=ON -DENABLE_SHARED=ON -DENABLE_GIO=ON -DENABLE_THUMBNAILER=ON .
- cmake --build .
- CTEST_OUTPUT_ON_FAILURE=1 ctest

addons:
  coverity_scan:
    project:
      name: "dirkvdb/ffmpegthumbnailer"
      description: "Build submitted via Travis CI"
    notification_email: dirk.vdb@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make -j4"
    branch_pattern: coverity_scan
